[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "wite2_tools"
version = "0.2.0"
description = "A specialized toolkit for WiTE2 data management."
readme = "ReadMe.md"
authors = [{name = "Mark L. Short"}]
dependencies = [
    "chardet>=5.2.0"
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0"
]